"""add dynasty_value table

Revision ID: 1d1ce0af4c71
Revises: 99f93f024073
Create Date: 2026-04-17 16:18:47.384025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1ce0af4c71'
down_revision: Union[str, None] = '99f93f024073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynasty_value',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fantasycalc_id', sa.Integer(), nullable=True),
    sa.Column('sleeper_id', sa.String(length=20), nullable=True),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('team', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('overall_rank', sa.Integer(), nullable=True),
    sa.Column('position_rank', sa.Integer(), nullable=True),
    sa.Column('trend_30day', sa.Integer(), nullable=True),
    sa.Column('is_pick', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_name')
    )
    with op.batch_alter_table('dynasty_value', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dynasty_value_sleeper_id'), ['sleeper_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynasty_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dynasty_value_sleeper_id'))

    op.drop_table('dynasty_value')
    # ### end Alembic commands ###
