"""add_keeper_cost_and_draft_session

Revision ID: 5e62b2f30854
Revises: 1d1ce0af4c71
Create Date: 2026-04-17 17:51:41.915637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e62b2f30854'
down_revision: Union[str, None] = '1d1ce0af4c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('num_teams', sa.Integer(), nullable=False),
    sa.Column('num_rounds', sa.Integer(), nullable=False),
    sa.Column('user_team_slot', sa.Integer(), nullable=False),
    sa.Column('drafted_ids', sa.Text(), nullable=False),
    sa.Column('queued_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keeper_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('dynasty_value_id', sa.Integer(), nullable=True),
    sa.Column('keeper_round', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dynasty_value_id'], ['dynasty_value.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keeper_cost')
    op.drop_table('draft_session')
    # ### end Alembic commands ###
