"""add_game_line_table

Revision ID: 99f93f024073
Revises: f17c787e8d86
Create Date: 2026-03-31 18:25:21.128157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f93f024073'
down_revision: Union[str, None] = 'f17c787e8d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=5), nullable=False),
    sa.Column('away_team', sa.String(length=5), nullable=False),
    sa.Column('game_total', sa.Float(), nullable=True),
    sa.Column('home_spread', sa.Float(), nullable=True),
    sa.Column('home_implied_total', sa.Float(), nullable=True),
    sa.Column('away_implied_total', sa.Float(), nullable=True),
    sa.Column('is_dome', sa.Boolean(), nullable=False),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('precip_probability', sa.Integer(), nullable=True),
    sa.Column('weather_flag', sa.Boolean(), nullable=False),
    sa.Column('game_date', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week', 'home_team', 'away_team', name='uq_gameline_week_home_away')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_line')
    # ### end Alembic commands ###
