"""initial schema

Revision ID: f17c787e8d86
Revises: 
Create Date: 2026-03-22 16:04:38.079590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17c787e8d86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=5), nullable=False),
    sa.Column('position', sa.String(length=5), nullable=False),
    sa.Column('opponent_rank', sa.Integer(), nullable=True),
    sa.Column('dvp_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week', 'team', 'position', name='uq_matchup_week_team_pos')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nflverse_id', sa.String(length=20), nullable=False),
    sa.Column('sleeper_id', sa.String(length=10), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=5), nullable=True),
    sa.Column('team', sa.String(length=5), nullable=True),
    sa.Column('injury_status', sa.String(length=20), nullable=True),
    sa.Column('practice_participation', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('injury_start_date', sa.String(length=10), nullable=True),
    sa.Column('week1_snap_pct', sa.Float(), nullable=True),
    sa.Column('week2_snap_pct', sa.Float(), nullable=True),
    sa.Column('week3_snap_pct', sa.Float(), nullable=True),
    sa.Column('week4_snap_pct', sa.Float(), nullable=True),
    sa.Column('week1_target_share', sa.Float(), nullable=True),
    sa.Column('week2_target_share', sa.Float(), nullable=True),
    sa.Column('week3_target_share', sa.Float(), nullable=True),
    sa.Column('week4_target_share', sa.Float(), nullable=True),
    sa.Column('week1_carry_share', sa.Float(), nullable=True),
    sa.Column('week2_carry_share', sa.Float(), nullable=True),
    sa.Column('week3_carry_share', sa.Float(), nullable=True),
    sa.Column('week4_carry_share', sa.Float(), nullable=True),
    sa.Column('matchup_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matchup_id'], ['matchup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_nflverse_id'), ['nflverse_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_player_sleeper_id'), ['sleeper_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_sleeper_id'))
        batch_op.drop_index(batch_op.f('ix_player_nflverse_id'))

    op.drop_table('player')
    op.drop_table('matchup')
    # ### end Alembic commands ###
